name: Create a pull Request for a Release Branch

on:
        workflow_dispatch:
        push:
            branches:
                - release/*

jobs:
    create_pr:
        runs-on: ubuntu-latest
        steps:
            # checkout the repository
            - name: Checkout the repo
              uses: actions/checkout@v3
              with:
                # we want the full history of the repo, not just the most recent commit
                fetch-depth: 0
            # create a pull request (if one already doesn't exist)
            - name: Create Pull Request
              run: |
                # if pull request doesn't exist
                pr_list=$(gh pr list --base "$GITHUB_BASE_REF" --json number --jq '.[] | .number')
                if [ -n "$pr_list" ]; then
                    echo "Pull request for branch $GITHUB_BASE_REF already exists."
                else
                    gh pr create --fill --draft --base live
                fi    
              env:
                # use github token from checkout
                GITHUB_TOKEN: ${{ github.token }}