name: Pyton Pytest Testing

on:
    pull_request:
        branches:
            - develop
            - live

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            # checkout the repo: https://github.com/marketplace/actions/checkout
            - uses: actions/checkout@v3
            # set up python
            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                python-version: "3.x"
            # install requirements
            - name: Install dependancies
              run:
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            # run PyTest
            - name: Test with pytest
              run: pytest
